window.browserDetect={init:function(){this.browser=this.searchString(this.dataBrowser)||"Unknown Browser";this.version=this.searchVersion(navigator.userAgent)||this.searchVersion(navigator.appVersion)||"Unknown Version";this.OS=this.searchString(this.dataOS)||"Unknown OS"},searchString:function(b){for(var a=0;a<b.length;a++){var c=b[a].string,d=b[a].prop;this.versionSearchString=b[a].versionSearch||b[a].identity;if(c){if(-1!=c.indexOf(b[a].subString))return b[a].identity}else if(d)return b[a].identity}},
searchVersion:function(b){var a=b.indexOf(this.versionSearchString);if(-1!=a)return parseFloat(b.substring(a+this.versionSearchString.length+1))},dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{prop:window.opera,identity:"Opera",versionSearch:"Version"},{string:navigator.vendor,subString:"iCab",
identity:"iCab"},{string:navigator.vendor,subString:"KDE",identity:"Konqueror"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,subString:"Gecko",identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,subString:"Mozilla",
identity:"Netscape",versionSearch:"Mozilla"}],dataOS:[{string:navigator.userAgent,subString:"Windows Phone",identity:"Windows Phone"},{string:navigator.platform,subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.userAgent,subString:"iPhone",identity:"iPhone/iPod"},{string:navigator.userAgent,subString:"iPad",identity:"iPad"},{string:navigator.userAgent,subString:"Android",identity:"Android"},{string:navigator.platform,subString:"Linux",
identity:"Linux"}]};window.browserDetect.init();

jQuery.effects||function(e,w){var x=!1!==e.uiBackCompat;e.effects={effect:{}};var f=jQuery,q=function(a,b,c){var d=y[b.type]||{};return null==a?c||!b.def?null:b.def:(a=d.floor?~~a:parseFloat(a),isNaN(a)?b.def:d.mod?(a+d.mod)%d.mod:0>a?0:d.max<a?d.max:a)},z=function(a){var b=i(),c=b._rgba=[];return a=a.toLowerCase(),j(D,function(d,e){var h,k=e.re.exec(a),k=k&&e.parse(k),l=e.space||"rgba";if(k)return h=b[l](k),b[m[l].cache]=h[m[l].cache],c=b._rgba=h._rgba,!1}),c.length?("0,0,0,0"===c.join()&&f.extend(c,
r.transparent),b):r[a]},t=function(a,b,c){return c=(c+1)%1,1>6*c?a+6*(b-a)*c:1>2*c?b:2>3*c?a+6*(b-a)*(2/3-c):a},E=/^([\-+])=\s*(\d+\.?\d*)/,D=[{re:/rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*(?:,\s*(\d+(?:\.\d+)?)\s*)?\)/,parse:function(a){return[a[1],a[2],a[3],a[4]]}},{re:/rgba?\(\s*(\d+(?:\.\d+)?)\%\s*,\s*(\d+(?:\.\d+)?)\%\s*,\s*(\d+(?:\.\d+)?)\%\s*(?:,\s*(\d+(?:\.\d+)?)\s*)?\)/,parse:function(a){return[2.55*a[1],2.55*a[2],2.55*a[3],a[4]]}},{re:/#([a-f0-9]{2})([a-f0-9]{2})([a-f0-9]{2})/,
parse:function(a){return[parseInt(a[1],16),parseInt(a[2],16),parseInt(a[3],16)]}},{re:/#([a-f0-9])([a-f0-9])([a-f0-9])/,parse:function(a){return[parseInt(a[1]+a[1],16),parseInt(a[2]+a[2],16),parseInt(a[3]+a[3],16)]}},{re:/hsla?\(\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\%\s*,\s*(\d+(?:\.\d+)?)\%\s*(?:,\s*(\d+(?:\.\d+)?)\s*)?\)/,space:"hsla",parse:function(a){return[a[1],a[2]/100,a[3]/100,a[4]]}}],i=f.Color=function(a,b,c,d){return new f.Color.fn.parse(a,b,c,d)},m={rgba:{props:{red:{idx:0,type:"byte"},
green:{idx:1,type:"byte"},blue:{idx:2,type:"byte"}}},hsla:{props:{hue:{idx:0,type:"degrees"},saturation:{idx:1,type:"percent"},lightness:{idx:2,type:"percent"}}}},y={"byte":{floor:!0,max:255},percent:{max:1},degrees:{mod:360,floor:!0}},A=i.support={},B=f("<p>")[0],r,j=f.each;B.style.cssText="background-color:rgba(1,1,1,.5)";A.rgba=-1<B.style.backgroundColor.indexOf("rgba");j(m,function(a,b){b.cache="_"+a;b.props.alpha={idx:3,type:"percent",def:1}});i.fn=f.extend(i.prototype,{parse:function(a,b,c,
d){if(void 0===a)return this._rgba=[null,null,null,null],this;if(a.jquery||a.nodeType)a=f(a).css(b),b=void 0;var g=this,h=f.type(a),k=this._rgba=[];void 0!==b&&(a=[a,b,c,d],h="array");if("string"===h)return this.parse(z(a)||r._default);if("array"===h)return j(m.rgba.props,function(b,c){k[c.idx]=q(a[c.idx],c)}),this;if("object"===h)return a instanceof i?j(m,function(b,c){a[c.cache]&&(g[c.cache]=a[c.cache].slice())}):j(m,function(b,c){var d=c.cache;j(c.props,function(b,e){if(!g[d]&&c.to){if("alpha"===
b||null==a[b])return;g[d]=c.to(g._rgba)}g[d][e.idx]=q(a[b],e,!0)});g[d]&&0>e.inArray(null,g[d].slice(0,3))&&(g[d][3]=1,c.from&&(g._rgba=c.from(g[d])))}),this},is:function(a){var b=i(a),c=!0,d=this;return j(m,function(a,e){var k,l=b[e.cache];return l&&(k=d[e.cache]||e.to&&e.to(d._rgba)||[],j(e.props,function(a,b){if(null!=l[b.idx])return c=l[b.idx]===k[b.idx],c})),c}),c},_space:function(){var a=[],b=this;return j(m,function(c,d){b[d.cache]&&a.push(c)}),a.pop()},transition:function(a,b){var c=i(a),
d=c._space(),e=m[d],h=0===this.alpha()?i("transparent"):this,k=h[e.cache]||e.to(h._rgba),l=k.slice();return c=c[e.cache],j(e.props,function(a,d){var e=d.idx,g=k[e],h=c[e],f=y[d.type]||{};null!==h&&(null===g?l[e]=h:(f.mod&&(h-g>f.mod/2?g+=f.mod:g-h>f.mod/2&&(g-=f.mod)),l[e]=q((h-g)*b+g,d)))}),this[d](l)},blend:function(a){if(1===this._rgba[3])return this;var b=this._rgba.slice(),c=b.pop(),d=i(a)._rgba;return i(f.map(b,function(a,b){return(1-c)*d[b]+c*a}))},toRgbaString:function(){var a="rgba(",b=f.map(this._rgba,
function(a,b){return null==a?2<b?1:0:a});return 1===b[3]&&(b.pop(),a="rgb("),a+b.join()+")"},toHslaString:function(){var a="hsla(",b=f.map(this.hsla(),function(a,b){return null==a&&(a=2<b?1:0),b&&3>b&&(a=Math.round(100*a)+"%"),a});return 1===b[3]&&(b.pop(),a="hsl("),a+b.join()+")"},toHexString:function(a){var b=this._rgba.slice(),c=b.pop();return a&&b.push(~~(255*c)),"#"+f.map(b,function(a){return a=(a||0).toString(16),1===a.length?"0"+a:a}).join("")},toString:function(){return 0===this._rgba[3]?
"transparent":this.toRgbaString()}});i.fn.parse.prototype=i.fn;m.hsla.to=function(a){if(null==a[0]||null==a[1]||null==a[2])return[null,null,null,a[3]];var b=a[0]/255,c=a[1]/255,d=a[2]/255,a=a[3],e=Math.max(b,c,d),h=Math.min(b,c,d),k=e-h,l=e+h,p=0.5*l,f,n;return h===e?f=0:b===e?f=60*(c-d)/k+360:c===e?f=60*(d-b)/k+120:f=60*(b-c)/k+240,0===p||1===p?n=p:0.5>=p?n=k/l:n=k/(2-l),[Math.round(f)%360,n,p,null==a?1:a]};m.hsla.from=function(a){if(null==a[0]||null==a[1]||null==a[2])return[null,null,null,a[3]];
var b=a[0]/360,c=a[1],d=a[2],a=a[3],c=0.5>=d?d*(1+c):d+c-d*c,d=2*d-c;return[Math.round(255*t(d,c,b+1/3)),Math.round(255*t(d,c,b)),Math.round(255*t(d,c,b-1/3)),a]};j(m,function(a,b){var c=b.props,d=b.cache,e=b.to,h=b.from;i.fn[a]=function(a){e&&!this[d]&&(this[d]=e(this._rgba));if(void 0===a)return this[d].slice();var b,p=f.type(a),F="array"===p||"object"===p?a:arguments,n=this[d].slice();return j(c,function(a,b){var c=F["object"===p?a:b.idx];null==c&&(c=n[b.idx]);n[b.idx]=q(c,b)}),h?(b=i(h(n)),b[d]=
n,b):i(n)};j(c,function(b,c){i.fn[b]||(i.fn[b]=function(d){var e=f.type(d),g="alpha"===b?this._hsla?"hsla":"rgba":a,h=this[g](),i=h[c.idx],j;return"undefined"===e?i:("function"===e&&(d=d.call(this,i),e=f.type(d)),null==d&&c.empty?this:("string"===e&&(j=E.exec(d),j&&(d=i+parseFloat(j[2])*("+"===j[1]?1:-1))),h[c.idx]=d,this[g](h)))})})});j("backgroundColor borderBottomColor borderLeftColor borderRightColor borderTopColor color columnRuleColor outlineColor textDecorationColor textEmphasisColor".split(" "),
function(a,b){f.cssHooks[b]={set:function(a,d){var e,h="";if("string"!==f.type(d)||(e=z(d))){d=i(e||d);if(!A.rgba&&1!==d._rgba[3]){for(e="backgroundColor"===b?a.parentNode:a;(""===h||"transparent"===h)&&e&&e.style;)try{h=f.css(e,"backgroundColor"),e=e.parentNode}catch(k){}d=d.blend(h&&"transparent"!==h?h:"_default")}d=d.toRgbaString()}try{a.style[b]=d}catch(l){}}};f.fx.step[b]=function(a){a.colorInit||(a.start=i(a.elem,b),a.end=i(a.end),a.colorInit=!0);f.cssHooks[b].set(a.elem,a.start.transition(a.end,
a.pos))}});f.cssHooks.borderColor={expand:function(a){var b={};return j(["Top","Right","Bottom","Left"],function(c,d){b["border"+d+"Color"]=a}),b}};r=f.Color.names={aqua:"#00ffff",black:"#000000",blue:"#0000ff",fuchsia:"#ff00ff",gray:"#808080",green:"#008000",lime:"#00ff00",maroon:"#800000",navy:"#000080",olive:"#808000",purple:"#800080",red:"#ff0000",silver:"#c0c0c0",teal:"#008080",white:"#ffffff",yellow:"#ffff00",transparent:[null,null,null,0],_default:"#ffffff"};var C=function(){var a=this.ownerDocument.defaultView?
this.ownerDocument.defaultView.getComputedStyle(this,null):this.currentStyle,b={},c,d;if(a&&a.length&&a[0]&&a[a[0]])for(d=a.length;d--;)c=a[d],"string"==typeof a[c]&&(b[e.camelCase(c)]=a[c]);else for(c in a)"string"==typeof a[c]&&(b[c]=a[c]);return b},G=["add","remove","toggle"],H={border:1,borderBottom:1,borderColor:1,borderLeft:1,borderRight:1,borderTop:1,borderWidth:1,margin:1,padding:1};e.each(["borderLeftStyle","borderRightStyle","borderBottomStyle","borderTopStyle"],function(a,b){e.fx.step[b]=
function(a){if("none"!==a.end&&!a.setAttr||1===a.pos&&!a.setAttr)jQuery.style(a.elem,b,a.end),a.setAttr=!0}});e.effects.animateClass=function(a,b,c,d){var g=e.speed(b,c,d);return this.queue(function(){var b=e(this),c=b.attr("class")||"",d,f=g.children?b.find("*").andSelf():b,f=f.map(function(){return{el:e(this),start:C.call(this)}});d=function(){e.each(G,function(c,d){a[d]&&b[d+"Class"](a[d])})};d();f=f.map(function(){this.end=C.call(this.el[0]);var a=this.start,b=this.end,c={},d,g;for(d in b)g=b[d],
a[d]!==g&&!H[d]&&(e.fx.step[d]||!isNaN(parseFloat(g)))&&(c[d]=g);return this.diff=c,this});b.attr("class",c);f=f.map(function(){var a=this,b=e.Deferred(),c=jQuery.extend({},g,{queue:!1,complete:function(){b.resolve(a)}});return this.el.animate(this.diff,c),b.promise()});e.when.apply(e,f.get()).done(function(){d();e.each(arguments,function(){var a=this.el;e.each(this.diff,function(b){a.css(b,"")})});g.complete.call(b[0])})})};e.fn.extend({_addClass:e.fn.addClass,addClass:function(a,b,c,d){return b?
e.effects.animateClass.call(this,{add:a},b,c,d):this._addClass(a)},_removeClass:e.fn.removeClass,removeClass:function(a,b,c,d){return b?e.effects.animateClass.call(this,{remove:a},b,c,d):this._removeClass(a)},_toggleClass:e.fn.toggleClass,toggleClass:function(a,b,c,d,g){return"boolean"==typeof b||b===w?c?e.effects.animateClass.call(this,b?{add:a}:{remove:a},c,d,g):this._toggleClass(a,b):e.effects.animateClass.call(this,{toggle:a},b,c,d)},switchClass:function(a,b,c,d,g){return e.effects.animateClass.call(this,
{add:b,remove:a},c,d,g)}});var s=function(a,b,c,d){e.isPlainObject(a)&&(b=a,a=a.effect);a={effect:a};null==b&&(b={});e.isFunction(b)&&(d=b,c=null,b={});if("number"==typeof b||e.fx.speeds[b])d=c,c=b,b={};return e.isFunction(c)&&(d=c,c=null),b&&e.extend(a,b),c=c||b.duration,a.duration=e.fx.off?0:"number"==typeof c?c:c in e.fx.speeds?e.fx.speeds[c]:e.fx.speeds._default,a.complete=d||b.complete,a},u=function(a){return!a||"number"==typeof a||e.fx.speeds[a]?!0:"string"==typeof a&&!e.effects.effect[a]?x&&
e.effects[a]?!1:!0:!1};e.extend(e.effects,{version:"1.9.2",save:function(a,b){for(var c=0;c<b.length;c++)null!==b[c]&&a.data("ui-effects-"+b[c],a[0].style[b[c]])},restore:function(a,b){var c,d;for(d=0;d<b.length;d++)null!==b[d]&&(c=a.data("ui-effects-"+b[d]),c===w&&(c=""),a.css(b[d],c))},setMode:function(a,b){return"toggle"===b&&(b=a.is(":hidden")?"show":"hide"),b},getBaseline:function(a,b){var c,d;switch(a[0]){case "top":c=0;break;case "middle":c=0.5;break;case "bottom":c=1;break;default:c=a[0]/
b.height}switch(a[1]){case "left":d=0;break;case "center":d=0.5;break;case "right":d=1;break;default:d=a[1]/b.width}return{x:d,y:c}},createWrapper:function(a){if(a.parent().is(".ui-effects-wrapper"))return a.parent();var b={width:a.outerWidth(!0),height:a.outerHeight(!0),"float":a.css("float")},c=e("<div></div>").addClass("ui-effects-wrapper").css({fontSize:"100%",background:"transparent",border:"none",margin:0,padding:0}),d={width:a.width(),height:a.height()},g=document.activeElement;try{g.id}catch(f){g=
document.body}return a.wrap(c),(a[0]===g||e.contains(a[0],g))&&e(g).focus(),c=a.parent(),"static"===a.css("position")?(c.css({position:"relative"}),a.css({position:"relative"})):(e.extend(b,{position:a.css("position"),zIndex:a.css("z-index")}),e.each(["top","left","bottom","right"],function(c,d){b[d]=a.css(d);isNaN(parseInt(b[d],10))&&(b[d]="auto")}),a.css({position:"relative",top:0,left:0,right:"auto",bottom:"auto"})),a.css(d),c.css(b).show()},removeWrapper:function(a){var b=document.activeElement;
return a.parent().is(".ui-effects-wrapper")&&(a.parent().replaceWith(a),(a[0]===b||e.contains(a[0],b))&&e(b).focus()),a},setTransition:function(a,b,c,d){return d=d||{},e.each(b,function(b,e){var f=a.cssUnit(e);0<f[0]&&(d[e]=f[0]*c+f[1])}),d}});e.fn.extend({effect:function(){function a(a){function c(){e.isFunction(f)&&f.call(d[0]);e.isFunction(a)&&a()}var d=e(this),f=b.complete,h=b.mode;(d.is(":hidden")?"hide"===h:"show"===h)?c():g.call(d[0],b,c)}var b=s.apply(this,arguments),c=b.mode,d=b.queue,g=
e.effects.effect[b.effect],f=!g&&x&&e.effects[b.effect];return e.fx.off||!g&&!f?c?this[c](b.duration,b.complete):this.each(function(){b.complete&&b.complete.call(this)}):g?!1===d?this.each(a):this.queue(d||"fx",a):f.call(this,{options:b,duration:b.duration,callback:b.complete,mode:b.mode})},_show:e.fn.show,show:function(a){if(u(a))return this._show.apply(this,arguments);var b=s.apply(this,arguments);return b.mode="show",this.effect.call(this,b)},_hide:e.fn.hide,hide:function(a){if(u(a))return this._hide.apply(this,
arguments);var b=s.apply(this,arguments);return b.mode="hide",this.effect.call(this,b)},__toggle:e.fn.toggle,toggle:function(a){if(u(a)||"boolean"==typeof a||e.isFunction(a))return this.__toggle.apply(this,arguments);var b=s.apply(this,arguments);return b.mode="toggle",this.effect.call(this,b)},cssUnit:function(a){var b=this.css(a),c=[];return e.each(["em","px","%","pt"],function(a,e){0<b.indexOf(e)&&(c=[parseFloat(b),e])}),c}});var v={};e.each(["Quad","Cubic","Quart","Quint","Expo"],function(a,b){v[b]=
function(b){return Math.pow(b,a+2)}});e.extend(v,{Sine:function(a){return 1-Math.cos(a*Math.PI/2)},Circ:function(a){return 1-Math.sqrt(1-a*a)},Elastic:function(a){return 0===a||1===a?a:-Math.pow(2,8*(a-1))*Math.sin((80*(a-1)-7.5)*Math.PI/15)},Back:function(a){return a*a*(3*a-2)},Bounce:function(a){for(var b,c=4;a<((b=Math.pow(2,--c))-1)/11;);return 1/Math.pow(4,3-c)-7.5625*Math.pow((3*b-2)/22-a,2)}});e.each(v,function(a,b){e.easing["easeIn"+a]=b;e.easing["easeOut"+a]=function(a){return 1-b(1-a)};
e.easing["easeInOut"+a]=function(a){return 0.5>a?b(2*a)/2:1-b(-2*a+2)/2}})}(jQuery);

(function(a,e,n){a.fn.backstretch=function(c,b){return(c===n||0===c.length)&&a.error("No images were supplied for Backstretch"),0===a(e).scrollTop()&&e.scrollTo(0,0),this.each(function(){var e=a(this),g=e.data("backstretch");g&&(b=a.extend(g.options,b),g.destroy(!0));g=new p(this,c,b);e.data("backstretch",g)})};a.backstretch=function(c,b){return a("body").backstretch(c,b).data("backstretch")};a.expr[":"].backstretch=function(c){return a(c).data("backstretch")!==n};a.fn.backstretch.defaults={centeredX:!0,
centeredY:!0,duration:5E3,fade:0};var q={left:0,top:0,overflow:"hidden",margin:0,padding:0,height:"100%",width:"100%",zIndex:-999999},r={position:"absolute",display:"none",margin:0,padding:0,border:"none",width:"auto",height:"auto",maxWidth:"none",zIndex:-999999},p=function(c,b,d){this.options=a.extend({},a.fn.backstretch.defaults,d||{});this.images=a.isArray(b)?b:[b];a.each(this.images,function(){a("<img />")[0].src=this});this.isBody=c===document.body;this.$container=a(c);this.$wrap=a('<div class="backstretch"></div>').css(q).appendTo(this.$container);
this.$root=this.isBody?k?a(e):a(document):this.$container;this.isBody||(c=this.$container.css("position"),b=this.$container.css("zIndex"),this.$container.css({position:"static"===c?"relative":c,zIndex:"auto"===b?0:b,background:"none"}),this.$wrap.css({zIndex:-999998}));this.$wrap.css({position:this.isBody&&k?"fixed":"absolute"});this.index=0;this.show(this.index);a(e).on("resize.backstretch",a.proxy(this.resize,this)).on("orientationchange.backstretch",a.proxy(function(){this.isBody&&0===e.pageYOffset&&
(e.scrollTo(0,1),this.resize())},this))};p.prototype={resize:function(){try{var a={left:0,top:0},b=this.isBody?this.$root.width():this.$root.innerWidth(),d=b,g=this.isBody?e.innerHeight?e.innerHeight:this.$root.height():this.$root.innerHeight(),i=d/this.$img.data("ratio"),f;i>=g?(f=(i-g)/2,this.options.centeredY&&(a.top="-"+f+"px")):(i=g,d=i*this.$img.data("ratio"),f=(d-b)/2,this.options.centeredX&&(a.left="-"+f+"px"));this.$wrap.css({width:b,height:g}).find("img:not(.deleteable)").css({width:d,height:i}).css(a)}catch(h){}return this},
show:function(c){if(!(Math.abs(c)>this.images.length-1)){this.index=c;var b=this,d=b.$wrap.find("img").addClass("deleteable"),e=a.Event("backstretch.show",{relatedTarget:b.$container[0]});return clearInterval(b.interval),b.$img=a("<img />").css(r).bind("load",function(c){var f=this.width||a(c.target).width(),c=this.height||a(c.target).height();a(this).data("ratio",f/c);b.resize();a(this).fadeIn(b.options.speed||b.options.fade,function(){d.remove();b.paused||b.cycle();b.$container.trigger(e)})}).appendTo(b.$wrap),
b.$img.attr("src",b.images[c]),b}},next:function(){return this.show(this.index<this.images.length-1?this.index+1:0)},prev:function(){return this.show(0===this.index?this.images.length-1:this.index-1)},pause:function(){return this.paused=!0,this},resume:function(){return this.paused=!1,this.next(),this},cycle:function(){return 1<this.images.length&&(clearInterval(this.interval),this.interval=setInterval(a.proxy(function(){this.paused||this.next()},this),this.options.duration)),this},destroy:function(c){a(e).off("resize.backstretch orientationchange.backstretch");
clearInterval(this.interval);c||this.$wrap.remove();this.$container.removeData("backstretch")}};var k,f=navigator.userAgent,l=navigator.platform,d=f.match(/AppleWebKit\/([0-9]+)/),d=!!d&&d[1],h=f.match(/Fennec\/([0-9]+)/),h=!!h&&h[1],m=f.match(/Opera Mobi\/([0-9]+)/),s=!!m&&m[1],j=f.match(/MSIE ([0-9]+)/),j=!!j&&j[1];k=!((-1<l.indexOf("iPhone")||-1<l.indexOf("iPad")||-1<l.indexOf("iPod"))&&d&&534>d||e.operamini&&"[object OperaMini]"==={}.toString.call(e.operamini)||m&&7458>s||-1<f.indexOf("Android")&&
d&&533>d||h&&6>h||"palmGetResource"in e&&d&&534>d||-1<f.indexOf("MeeGo")&&-1<f.indexOf("NokiaBrowser/8.5.0")||j&&6>=j)})(jQuery,window);
